Add icon for xfce4-terminal
justbuchanan/i3scripts pull request #1
Opened 2017-08-24 10:32 UTC by fredden

2017-08-24 21:47 UTC, justbuchanan commented
Thanks for the PR! I have a few suggestions I'll make inline.

2017-08-24 21:55 UTC, fredden commented
Odd, I'd intended this PR to be only adding the icon, and was going to do another for the other commits.

2017-08-24 21:56 UTC, justbuchanan requested changes

2017-08-24 21:56 UTC, justbuchanan commented on autoname_workspaces.py
> +            continue
What happens if a window opens or closes on a workspace that isn't currently focused? For example, sometimes I have a software update program running on a hidden workspace that closes itself when done.

2017-08-24 21:56 UTC, justbuchanan commented on autoname_workspaces.py
> +        rename_workspaces(i3)
I think we only want to trigger a rename when a workspace is created or deleted. Similar to the `window_event_handler()`, we should check the value of `e.change`.

See the docs here for what values "change" could be https://i3wm.org/docs/ipc.html#_events.

2017-08-24 21:58 UTC, justbuchanan commented on autoname_workspaces.py
> +        rename_workspaces(i3)
You can also try this experimentally by saving this chunk of code into a python file and running it:

~~~{.py}
import i3ipc

def handle(i3, e):
    print(e)
    print(e.change)

i3 = i3ipc.Connection()
i3.on('workspace', handle)
i3.main()
~~~

2017-08-27 03:52 UTC, fredden commented
Thanks for the comments. I'll close this and submit only what I intended to be included in this pull request, and we can try again.

2017-08-27 03:52 UTC, closed without merging